spring:
  application:
    name: TaskScheduler
  datasource:
      url: jdbc:postgresql://localhost:5432/tasksdb
      username: postgres
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

